version: "3.9"
services:

  my-estate-api:
    image: eu.gcr.io/my-estate-377108/my-estate-api/my-estate-api:66287eb31ea32f8070ab26ac0d22dd2c2d8076c0
    depends_on:
      - mysqldb
    ports:
      - '3000:3000'
    env_file: ./.env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
    volumes:
    - .:/app
    - /app/node_modules
    command: npm run start:dev
  
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: $DB_PORT
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes: 
  db:
